config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :teams, controllers: {
    sessions:      'teams/sessions',
    passwords:     'teams/passwords',
    registrations: 'teams/registrations'
  }

  resources :posts, only: [:create, :index, :new, :show]
  resources :comments, only: :create
  resources :teams, only: [:index, :show]
  root 'teams#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="mx-auto alert alert-success text-center" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="mx-auto alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- footer -->
<div class="footer--bar">
  <div class="container mt-auto">&copy; 2019 ウイングカップ実行委員会</div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-dark py-0 nav--border">
  <div class="container">
    <%# ロゴ部分 %>
      <a class="navbar-brand" href="http://neezexp.sakura.ne.jp/wcHp/wcTop.html" target="aboutblank" rel="noopener"><img src="<%= asset_path "wcLogo.png" %>" alt="navber"></a>
    <%# メニュー %>
    <div class="justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item active my-auto">
          <% if team_signed_in? %>
            <%= link_to team_path(current_team.id), class: "nav-link mr-4" do %>
              <i class="fas fa-users fa-lg"></i> <%= current_team.name %>
            <% end %>
          <% else %>
            <%= link_to new_team_session_path, class: "nav-link mr-4" do %>
              <i class="fas fa-user-times fa-lg"></i> ログイン
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= search_form_for @q ,class: "nav-link form-inline mb-0" do |f|  %>
            <%= f.search_field :title_or_team_name_or_team_location_or_comments_body_cont, class: "form-control", placeholder: "検索" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>