config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :teams, controllers: {
    sessions:      'teams/sessions',
    passwords:     'teams/passwords',
    registrations: 'teams/registrations'
  }

  resources :posts, only: [:create, :index, :new, :show]
  resources :comments, only: :create
  resources :teams, only: [:index, :show]
  root 'teams#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :team, touch: true
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}

  scope :find_newest_post, -> (page) { order(updated_at: :desc).page(page).per(20) }
  scope :with_team_and_comment, -> { includes(team: [image_attachment: :blob], comments: [team: [image_attachment: :blob]]) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_team!
  before_action :set_post, only: [:edit, :update, :show]

  def index
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_team.posts.new(post_params)
    if @post.save
      redirect_to posts_path, notice: "スレッドを作成しました"
    else
      render :new
    end
  end

  def show
    @post = Post.with_team_and_comment.find(params[:id])
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= render "shared/errors", obj: post %>
<%= form_with model: post, local:true do |f| %>
  <div class="form-group mb-4">
    <h4><%= f.label :title %></h4>
    <%= f.text_area :title, placeholder: "必須 (100文字以内)", class: "form-control", rows: "5" %>
  </div>
  <p>
    <%= f.submit t(".post"), class: "btn btn-block btn-primary shadow" %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div class="container-fuluid">
  <div class="row mb-2">
    <%= link_to team_path(post.team) do %>
      <% if post.team.image.attached? %>
        <%= image_tag post.team.image.variant(resize_to_fill: [40, 40]).processed, class: "img-fluid rounded-circle mr-2" %>
      <% else %>
        <i class="fas fa-user-circle fa-2x mr-1"></i>
      <% end %>
        <%= post.team.name %>
    <% end %>
  </div>
</div>

<div class="card shadow mb-5">
  <div class="card-header bg-transparent ">
    <div class="row justify-content-between px-3">
      <p>タイトル</p>
      <p><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
    </div>
    <%= link_to post do %>
      <%= simple_format (post.title), class: "mx-4" %>
    <% end %>
  </div>

  <div class="card-body">
    <p>最新コメント (コメント全<%= post.comments.count %>件)</p>
    <% post.comments.last(1).each do |comment| %>
      <div class="row justify-content-between align-items-baseline px-3 mb-2">
        <div>
          <%= link_to team_path(comment.team) do %>
            <% if comment.team.image.attached? %>
              <%= image_tag comment.team.image.variant(resize_to_fill: [30, 30]).processed, class: "img-fluid rounded-circle mr-1" %>
            <% else %>
              <i class="fas fa-user-circle fa-2x mr-1"></i>
            <% end %>
            <%= comment.team.name %>
          <% end %>
        </div>
        <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
      </div>
      <p class="mx-4"><%= truncate(comment.body, length: 50) %></p>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mb-5">
  <div class="row justify-content-center my-5">
    <%= link_to t(".teams_index"), teams_path, class: "btn-lg btn-secondary col-3 text-center" %>
    <%= link_to t(".create_post"), new_post_path, class: "btn-lg btn-secondary col-3 text-center mx-1" %>
    <div class="btn-lg btn-primary col-3 text-center shadow"><%= t(".title") %></div>
  </div>
  
  <div class="col-lg-10 mx-auto">
    <%= render "shared/errors", obj: @comment %>
    <%= render @posts %>
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center my-5">
    <%= link_to t(".teams_index"), teams_path, class: "btn-lg btn-secondary col-3 text-center" %>
    <div class="btn-lg btn-primary col-3 text-center shadow mx-1"><%= t(".title") %></div>
    <%= link_to t(".posts_index"), posts_path, class: "btn-lg btn-secondary col-3 text-center" %>
  </div>

  <div class="col-lg-10 mx-auto">
    <%= render "form", post: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center my-5">
    <%= link_to t(".teams_index"), teams_path, class: "btn-lg btn-secondary col-3 text-center" %>
    <div class="btn-lg btn-primary col-3 text-center shadow mx-1"><%= t(".title") %></div>
    <%= link_to t(".posts_index"), posts_path, class: "btn-lg btn-secondary col-3 text-center" %>
  </div>

  <div class="col-lg-10 mx-auto">
    <%= render "shared/errors", obj: @comment %>
    <div class="row mb-2">
      <%= link_to team_path(@post.team) do %>
        <% if @post.team.image.attached? %>
          <%= image_tag @post.team.image.variant(resize_to_fill: [40, 40]).processed, class: "img-fluid rounded-circle mr-2" %>
        <% else %>
          <i class="fas fa-user-circle fa-2x"></i>
        <% end %>
          <%= @post.team.name %>
      <% end %>
    </div>

    <div class="card shadow-sm mb-4">
      <div class="card-header bg-transparent ">
        <div class="row justify-content-between px-3">
          <p>タイトル</p>
          <p><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
        </div>
        <%= simple_format (@post.title), class: "mx-4" %>
      </div>
  
      <div class="card-body">
        <p>コメント (全<%= @post.comments.count %>件)</p>
        <% @post.comments.each do |comment| %>
          <hr>
          <div class="row justify-content-between align-items-baseline px-3">
            <div>
              <%= link_to team_path(comment.team) do %>
                <% if comment.team.image.attached? %>
                  <%= image_tag comment.team.image.variant(resize_to_fill: [30, 30]).processed, class: "img-fluid rounded-circle mr-1" %>
                <% else %>
                  <i class="fas fa-user-circle fa-2x mr-1"></i>
                <% end %>
                <%= comment.team.name %>
              <% end %>
            </div>
            <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
          </div>
          <%= simple_format (comment.body), class: "mx-4 mt-2" %>
        <% end %>
      </div>
    </div>
  
    <div class="mb-5">
      <%= form_with model: @comment, url: comments_path, class: "row mx-auto ", local: true do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.text_area :body, class: "form-control px-4 mb-1", placeholder: "コメント入力(300文字以内)" %>
        <%= f.submit t(".submit"), class: "btn btn-block btn-primary shadow" %>
      <% end %>
    </div>
  </div>
</div>